import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './store/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className="white">
      <body className="w-full h-auto relative m-0 p-0 dark:bg-slate-900">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
